### ISSUE TITLE
Gnatcatcher Timeline Clarification

### ISSUE THREAD

**Issue by willertonc** [bslassey/ip-blindness#5]
Hello

At the footer of the Google Privacy Sandbox timeline (https://privacysandbox.com/timeline/) is a secondary timeline indicating that gnatcatcher will reach scaled availability during the second half of 2022.

![image](https://user-images.githubusercontent.com/24571884/132397021-57f5a980-6de2-4ea2-aedd-1600c103acd1.png)

Does this mean that it will be rolled out as part of Chrome and IP address information will no longer be available in the second half of 2022? IF it doesn't mean this, when is it estimated that IP address information will no longer be available?

Thank you

**Comment by bslassey** [comment]
We added a footnote on the timeline to attempt to clarify this. 

> Earliest date of scaled availability represents the earliest date when Gnatcatcher could be made available to sites for broad use on an optional basis.

We don't have an estimate for when we'd move beyond this optional testing phase

**Comment by bslassey** [comment]
Deleting this issue per the request of the original poster and the fact that it doesn't represent a substantive contribution.
