### ISSUE TITLE
1st party clarification

### ISSUE THREAD

**Issue by keyo321** [bslassey/ip-blindness#7]
Hi @bslassey,

Thank you for sharing details about this proposal in today's W3C meeting.   I have a follow-up question and want additional clarification regarding the question about site operators/1st party owners/1st party sets.  As a publisher/site owner of somesite.com, will I see the original IP of users visiting somesite.com or will their IPs be proxied/masked for me as well?  

thanks

**Comment by bslassey** [comment]
If somesite.com is Willfully IP Blind (i.e. conforms to the policy we generate from the proposed principles) then it will have a direct connection and therefore have access to the original IP address. Otherwise the traffic will be routed through the Near-Path NAT and be masked.

**Comment by keyo321** [comment]
@bslassey Can you share additional details about how or who will be the governing entity to ensure a party is following the proposed principles?

**Comment by npdoty** [comment]
@keyo321 this explainer refers to signed attestations, audits and spot checking as ways to confirm following a particular policy:
https://github.com/bslassey/ip-blindness/blob/master/willful_ip_blindness.md
But if you have more questions, I think a separate, new issue would be a good way to manage that discussion.
